const api=(localStorage.getItem('interviewApi')||'http://127.0.0.1:8010').replace(/\/$/,'');const launch=new URLSearchParams(location.search).get('launch');let access=sessionStorage.getItem(`interview:${launch}`),stream,recorder,chunks=[],phase='gate',heartbeat,prepTimer,answerTimer,pcm=[],captureRate=0,audioContext,audioSource,audioProcessor,silentGain,questionAudio;
const $=id=>document.getElementById(id);const auth=()=>({Authorization:`Bearer ${access}`});
const call=async(path,opt={})=>{const r=await fetch(api+path,{headers:{'Content-Type':'application/json',...(opt.headers||{})},...opt});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.detail||'Có lỗi kết nối');return d};
const errorFrom=async r=>{const d=await r.json().catch(()=>({}));return d.detail||'Có lỗi kết nối Azure Speech'};
function fail(e){$('error').textContent=e.message||e}function end(message){clearInterval(heartbeat);clearInterval(prepTimer);clearInterval(answerTimer);questionAudio?.pause();stopAudioCapture();stream?.getTracks().forEach(t=>t.stop());$('gate').hidden=true;$('room').hidden=true;$('ended').hidden=false;$('endMessage').textContent=message}
async function load(){if(!launch)return fail('Thiếu link phỏng vấn.');try{const d=await call(`/v1/public/launch/${launch}`);$('title').textContent=`Phỏng vấn vị trí ${d.job_title}`;$('description').textContent=`Xin chào ${d.candidate_name}. Xác thực email để tiếp tục.`}catch(e){fail(e)}}
$('sendOtp').onclick=async()=>{try{await call(`/v1/public/launch/${launch}/otp`,{method:'POST',body:JSON.stringify({email:$('email').value})});$('otpBlock').hidden=false}catch(e){fail(e)}};
$('verifyOtp').onclick=async()=>{try{const d=await call(`/v1/public/launch/${launch}/verify`,{method:'POST',body:JSON.stringify({email:$('email').value,code:$('otp').value})});access=d.access_token;sessionStorage.setItem(`interview:${launch}`,access);await begin()}catch(e){fail(e)}};
async function begin(){try{await document.documentElement.requestFullscreen();stream=await navigator.mediaDevices.getUserMedia({video:true,audio:true});$('preview').srcObject=stream;const d=await call('/v1/participant/start',{method:'POST',headers:auth()});$('gate').hidden=true;$('room').hidden=false;phase='interview';heartbeat=setInterval(()=>call('/v1/participant/heartbeat',{method:'POST',headers:auth()}).catch(()=>end('Phiên bị kết thúc do mất kết nối.')),5000);showQuestion(d.question,d.prepare_seconds,d.answer_seconds).catch(e=>end(e.message))}catch(e){fail('Cần cho phép full-screen, camera và microphone để bắt đầu. '+e.message)}}
async function playAzureQuestion(question){$('status').textContent='AI đang đọc câu hỏi…';const r=await fetch(api+'/v1/participant/speech/synthesize',{method:'POST',headers:{...auth(),'Content-Type':'application/json'},body:JSON.stringify({question_number:question.number})});if(!r.ok)throw Error(await errorFrom(r));const url=URL.createObjectURL(await r.blob());questionAudio=new Audio(url);await new Promise((resolve,reject)=>{questionAudio.onended=()=>{URL.revokeObjectURL(url);resolve()};questionAudio.onerror=()=>{URL.revokeObjectURL(url);reject(Error('Không thể phát âm thanh từ Azure Text-to-Speech.'))};questionAudio.play().catch(reject)})}
async function showQuestion(question,prepare,answer){$('question').textContent=question.text;$('answerNow').hidden=true;$('endAnswer').disabled=true;$('transcript').value='';await playAzureQuestion(question);prepareAnswer(question,prepare,answer)}
function prepareAnswer(question,seconds,max){clearInterval(prepTimer);let n=seconds;phase='preparing';$('answerNow').hidden=false;$('answerNow').textContent='Trả lời ngay';$('status').textContent='Chuẩn bị trả lời';$('timer').textContent=`${n}s`;$('answerNow').onclick=()=>answer(question,max);if(!n)return answer(question,max);prepTimer=setInterval(()=>{n--;$('timer').textContent=`${n}s`;if(n<=0){clearInterval(prepTimer);answer(question,max)}},1000)}
function startAudioCapture(){pcm=[];audioContext=new AudioContext();captureRate=audioContext.sampleRate;audioSource=audioContext.createMediaStreamSource(stream);audioProcessor=audioContext.createScriptProcessor(4096,1,1);silentGain=audioContext.createGain();silentGain.gain.value=0;audioProcessor.onaudioprocess=e=>{if(phase==='answering')pcm.push(new Float32Array(e.inputBuffer.getChannelData(0)))};audioSource.connect(audioProcessor);audioProcessor.connect(silentGain);silentGain.connect(audioContext.destination)}
function stopAudioCapture(){if(!audioProcessor)return null;audioProcessor.disconnect();audioSource.disconnect();silentGain.disconnect();audioProcessor.onaudioprocess=null;audioProcessor=audioSource=silentGain=null;audioContext?.close();audioContext=null;return pcmToWav(pcm,captureRate)}
function pcmToWav(parts,inputRate){const length=parts.reduce((n,p)=>n+p.length,0);if(!length)return new Blob([],{type:'audio/wav'});const source=new Float32Array(length);let offset=0;for(const part of parts){source.set(part,offset);offset+=part.length}const rate=16000,count=Math.max(1,Math.round(source.length*rate/inputRate)),buffer=new ArrayBuffer(44+count*2),view=new DataView(buffer);const put=(at,text)=>[...text].forEach((c,i)=>view.setUint8(at+i,c.charCodeAt(0)));put(0,'RIFF');view.setUint32(4,36+count*2,true);put(8,'WAVEfmt ');view.setUint32(16,16,true);view.setUint16(20,1,true);view.setUint16(22,1,true);view.setUint32(24,rate,true);view.setUint32(28,rate*2,true);view.setUint16(32,2,true);view.setUint16(34,16,true);put(36,'data');view.setUint32(40,count*2,true);for(let i=0;i<count;i++){const pos=i*inputRate/rate,left=Math.floor(pos),right=Math.min(left+1,source.length-1),sample=source[left]+(source[right]-source[left])*(pos-left);view.setInt16(44+i*2,Math.max(-1,Math.min(1,sample))*0x7fff,true)}return new Blob([buffer],{type:'audio/wav'})}
function answer(question,max){if(phase==='answering')return;clearInterval(prepTimer);phase='answering';$('answerNow').hidden=true;$('endAnswer').disabled=false;$('status').textContent='Đang ghi hình và ghi âm cho Azure Speech-to-Text.';chunks=[];startAudioCapture();recorder=new MediaRecorder(stream);recorder.ondataavailable=e=>e.data.size&&chunks.push(e.data);recorder.start(500);let n=max;$('timer').textContent=`${n}s`;answerTimer=setInterval(()=>{n--;$('timer').textContent=`${n}s`;if(n<=0)finish(question)},1000);$('endAnswer').onclick=()=>finish(question)}
async function finish(question){if(phase!=='answering')return;phase='submitting';clearInterval(answerTimer);$('endAnswer').disabled=true;const wav=stopAudioCapture();const video=new Promise(resolve=>{recorder.onstop=()=>resolve(new Blob(chunks,{type:recorder.mimeType||'video/webm'}));recorder.stop()});video.then(blob=>fetch(api+'/v1/participant/videos',{method:'POST',headers:{...auth(),'Content-Type':blob.type,'X-Interview-Question-Number':String(question.number)},body:blob})).catch(()=>{});try{$('status').textContent='Azure Speech-to-Text đang xử lý câu trả lời…';const r=await fetch(api+'/v1/participant/speech/transcribe',{method:'POST',headers:{...auth(),'Content-Type':'audio/wav','X-Interview-Question-Number':String(question.number)},body:wav});if(!r.ok)throw Error(await errorFrom(r));const {text}=await r.json();$('transcript').value=text||'(Azure Speech không nhận diện được lời nói)';const d=await call('/v1/participant/answers',{method:'POST',headers:auth(),body:JSON.stringify({text})});if(d.status==='COMPLETED')end('Cảm ơn bạn. Video cuối đang được tải lên an toàn.');else showQuestion(d.question,d.prepare_seconds,d.answer_seconds).catch(e=>end(e.message))}catch(e){end(e.message)}}
document.addEventListener('visibilitychange',()=>{if(phase==='interview'||phase==='preparing'||phase==='answering')call('/v1/participant/terminate',{method:'POST',headers:auth(),body:JSON.stringify({reason:'TAB_HIDDEN'})}).finally(()=>end('Phiên đã kết thúc vì bạn rời khỏi tab.'))});document.addEventListener('fullscreenchange',()=>{if(!document.fullscreenElement&&(phase==='interview'||phase==='preparing'||phase==='answering'))call('/v1/participant/terminate',{method:'POST',headers:auth(),body:JSON.stringify({reason:'FULLSCREEN_EXIT'})}).finally(()=>end('Phiên đã kết thúc vì bạn thoát toàn màn hình.'))});load();
