const api=(localStorage.getItem('interviewApi')||window.INTERVIEW_WEB_CONFIG?.apiUrl||'http://127.0.0.1:8010').replace(/\/$/,'');const launch=new URLSearchParams(location.search).get('launch');let access=sessionStorage.getItem(`interview:${launch}`),stream,deviceTestStream,deviceReady=false,recorder,chunks=[],phase='guide',heartbeat,prepTimer,answerTimer,pcm=[],captureRate=0,audioContext,audioSource,audioProcessor,silentGain,questionAudio,videoUploads=[];
const $=id=>document.getElementById(id);const auth=()=>({Authorization:`Bearer ${access}`});
const detailText=(detail,fallback)=>{if(typeof detail==='string'&&detail)return detail;if(Array.isArray(detail))return detail.map(item=>item?.msg||JSON.stringify(item)).join('; ');if(detail&&typeof detail==='object')return detail.message||detail.msg||JSON.stringify(detail);return fallback};
const call=async(path,opt={})=>{const r=await fetch(api+path,{...opt,headers:{'Content-Type':'application/json',...(opt.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(detailText(d.detail,'Có lỗi kết nối'));return d};
const errorFrom=async r=>{const d=await r.json().catch(()=>({}));return detailText(d.detail,'Có lỗi kết nối dịch vụ giọng nói')};
function fail(e){const message=e.message||e;if(!$('authStep').hidden)$('error').textContent=message;else $('description').textContent=message}
function stopDeviceTest(){deviceTestStream?.getTracks().forEach(track=>track.stop());deviceTestStream=null;$('devicePreview').srcObject=null;$('previewPlaceholder').hidden=false}
function setDeviceStatus(id,state){$(id).classList.remove('is-ok','is-error');if(state)$(id).classList.add(state)}
function updateContinue(){ $('continueToAuth').disabled=!(deviceReady&&$('acknowledge').checked) }
function end(message,state='ended'){phase=state;clearInterval(heartbeat);clearInterval(prepTimer);clearInterval(answerTimer);questionAudio?.pause();stopAudioCapture();stopDeviceTest();stream?.getTracks().forEach(t=>t.stop());$('gate').hidden=true;$('room').hidden=true;$('ended').hidden=false;$('ended').dataset.state=state;$('endMessage').textContent=message}
async function load(){if(!launch)return fail('Thiếu link phỏng vấn. Vui lòng mở lại đường dẫn do nhà tuyển dụng cung cấp.');const browserSupported=Boolean(navigator.mediaDevices?.getUserMedia&&window.MediaRecorder&&document.fullscreenEnabled);setDeviceStatus('browserStatus',browserSupported?'is-ok':'is-error');try{const d=await call(`/v1/public/launch/${launch}`);$('description').textContent=`Xin chào ${d.candidate_name}. Đây là buổi phỏng vấn cho vị trí ${d.job_title}. Hãy dành một phút để chuẩn bị trước khi bắt đầu.`;$('authDescription').textContent=`Chúng tôi sẽ gửi mã xác thực đến email bạn đã dùng để ứng tuyển vị trí ${d.job_title}.`;if(d.max_questions){$('questionCount').textContent=`Tối đa ${d.max_questions} câu hỏi`;$('estimatedTime').textContent=`Khoảng ${Math.max(3,Math.ceil(d.max_questions*1.5))} phút`}}catch(e){fail(e)}}
$('checkDevices').onclick=async()=>{const button=$('checkDevices');$('deviceError').textContent='';button.disabled=true;button.textContent='Đang kiểm tra…';stopDeviceTest();deviceReady=false;updateContinue();setDeviceStatus('cameraStatus');setDeviceStatus('microphoneStatus');try{if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder||!document.fullscreenEnabled)throw Error('Trình duyệt chưa hỗ trợ đầy đủ. Vui lòng dùng phiên bản Chrome hoặc Edge mới nhất trên máy tính.');deviceTestStream=await navigator.mediaDevices.getUserMedia({video:true,audio:true});const cameraOk=deviceTestStream.getVideoTracks().some(track=>track.readyState==='live');const microphoneOk=deviceTestStream.getAudioTracks().some(track=>track.readyState==='live');setDeviceStatus('cameraStatus',cameraOk?'is-ok':'is-error');setDeviceStatus('microphoneStatus',microphoneOk?'is-ok':'is-error');if(!cameraOk||!microphoneOk)throw Error('Không tìm thấy đầy đủ camera và microphone.');$('devicePreview').srcObject=deviceTestStream;$('previewPlaceholder').hidden=true;deviceReady=true;$('deviceBadge').textContent='Sẵn sàng';$('deviceBadge').classList.add('is-ready');button.textContent='Kiểm tra lại thiết bị'}catch(e){stopDeviceTest();$('deviceBadge').textContent='Cần kiểm tra lại';$('deviceBadge').classList.remove('is-ready');$('deviceError').textContent=e.name==='NotAllowedError'?'Bạn cần cho phép truy cập camera và microphone trong trình duyệt.':e.message;button.textContent='Thử kiểm tra lại'}finally{button.disabled=false;updateContinue()}};
$('acknowledge').onchange=updateContinue;
$('continueToAuth').onclick=()=>{if(!deviceReady||!$('acknowledge').checked)return;stopDeviceTest();$('guideStep').hidden=true;$('authStep').hidden=false;phase='gate';window.scrollTo({top:0,behavior:'smooth'});$('email').focus()};
$('backToGuide').onclick=()=>{$('authStep').hidden=true;$('guideStep').hidden=false;phase='guide';window.scrollTo({top:0,behavior:'smooth'})};
$('sendOtp').onclick=async()=>{const button=$('sendOtp'),label=button.textContent;$('error').textContent='';button.disabled=true;button.textContent='Đang gửi…';try{await call(`/v1/public/launch/${launch}/otp`,{method:'POST',body:JSON.stringify({email:$('email').value})});$('otpBlock').hidden=false;$('authDescription').textContent='Mã OTP đã được gửi. Vui lòng kiểm tra hộp thư đến và thư rác.';$('otp').focus()}catch(e){fail(e)}finally{button.disabled=false;button.textContent=label}};
$('verifyOtp').onclick=async()=>{const button=$('verifyOtp');$('error').textContent='';button.disabled=true;button.textContent='Đang xác thực…';try{await document.documentElement.requestFullscreen();stream=await navigator.mediaDevices.getUserMedia({video:true,audio:true});if(!access){const d=await call(`/v1/public/launch/${launch}/verify`,{method:'POST',body:JSON.stringify({email:$('email').value,code:$('otp').value})});access=d.access_token;sessionStorage.setItem(`interview:${launch}`,access)}await begin()}catch(e){stream?.getTracks().forEach(track=>track.stop());stream=null;if(document.fullscreenElement)await document.exitFullscreen().catch(()=>{});fail(e.name==='NotAllowedError'?'Cần cho phép camera, microphone và chế độ toàn màn hình để bắt đầu.':e)}finally{button.disabled=false;button.textContent='Xác thực và bắt đầu phỏng vấn'}};
async function begin(){$('preview').srcObject=stream;const d=await call('/v1/participant/start',{method:'POST',headers:auth()});$('gate').hidden=true;$('room').hidden=false;phase='interview';heartbeat=setInterval(()=>call('/v1/participant/heartbeat',{method:'POST',headers:auth()}).catch(()=>end('Phiên bị kết thúc do mất kết nối.')),5000);showQuestion(d.question,d.prepare_seconds,d.answer_seconds).catch(e=>end(e.message))}
async function playSpeechQuestion(question){$('status').textContent='AI đang đọc câu hỏi…';const r=await fetch(api+'/v1/participant/speech/synthesize',{method:'POST',headers:{...auth(),'Content-Type':'application/json'},body:JSON.stringify({question_number:question.number})});if(!r.ok)throw Error(await errorFrom(r));const url=URL.createObjectURL(await r.blob());questionAudio=new Audio(url);await new Promise((resolve,reject)=>{questionAudio.onended=()=>{URL.revokeObjectURL(url);resolve()};questionAudio.onerror=()=>{URL.revokeObjectURL(url);reject(Error('Không thể phát âm thanh câu hỏi.'))};questionAudio.play().catch(reject)})}
async function showQuestion(question,prepare,answer){const questionElement=$('question');questionElement.textContent=question.text;questionElement.classList.toggle('is-long',question.text.length>180);questionElement.classList.toggle('is-very-long',question.text.length>320);questionElement.scrollTop=0;$('answerNow').hidden=true;$('endAnswer').disabled=true;$('transcript').value='';let warning='';try{await playSpeechQuestion(question)}catch(e){warning=`${e.message}. Bạn vẫn có thể đọc câu hỏi và tiếp tục.`}prepareAnswer(question,prepare,answer,warning)}
function prepareAnswer(question,seconds,max,warning=''){clearInterval(prepTimer);let n=seconds;phase='preparing';$('answerNow').hidden=false;$('answerNow').textContent='Trả lời ngay';$('status').textContent=warning||'Chuẩn bị trả lời';$('timer').textContent=`${n}s`;$('answerNow').onclick=()=>answer(question,max);if(!n)return answer(question,max);prepTimer=setInterval(()=>{n--;$('timer').textContent=`${n}s`;if(n<=0){clearInterval(prepTimer);answer(question,max)}},1000)}
function startAudioCapture(){pcm=[];audioContext=new AudioContext();captureRate=audioContext.sampleRate;audioSource=audioContext.createMediaStreamSource(stream);audioProcessor=audioContext.createScriptProcessor(4096,1,1);silentGain=audioContext.createGain();silentGain.gain.value=0;audioProcessor.onaudioprocess=e=>{if(phase==='answering')pcm.push(new Float32Array(e.inputBuffer.getChannelData(0)))};audioSource.connect(audioProcessor);audioProcessor.connect(silentGain);silentGain.connect(audioContext.destination)}
function stopAudioCapture(){if(!audioProcessor)return null;audioProcessor.disconnect();audioSource.disconnect();silentGain.disconnect();audioProcessor.onaudioprocess=null;audioProcessor=audioSource=silentGain=null;audioContext?.close();audioContext=null;return pcmToWav(pcm,captureRate)}
function pcmToWav(parts,inputRate){const length=parts.reduce((n,p)=>n+p.length,0);if(!length)return new Blob([],{type:'audio/wav'});const source=new Float32Array(length);let offset=0;for(const part of parts){source.set(part,offset);offset+=part.length}const rate=16000,count=Math.max(1,Math.round(source.length*rate/inputRate)),buffer=new ArrayBuffer(44+count*2),view=new DataView(buffer);const put=(at,text)=>[...text].forEach((c,i)=>view.setUint8(at+i,c.charCodeAt(0)));put(0,'RIFF');view.setUint32(4,36+count*2,true);put(8,'WAVEfmt ');view.setUint32(16,16,true);view.setUint16(20,1,true);view.setUint16(22,1,true);view.setUint32(24,rate,true);view.setUint32(28,rate*2,true);view.setUint16(32,2,true);view.setUint16(34,16,true);put(36,'data');view.setUint32(40,count*2,true);for(let i=0;i<count;i++){const pos=i*inputRate/rate,left=Math.floor(pos),right=Math.min(left+1,source.length-1),sample=source[left]+(source[right]-source[left])*(pos-left);view.setInt16(44+i*2,Math.max(-1,Math.min(1,sample))*0x7fff,true)}return new Blob([buffer],{type:'audio/wav'})}
function answer(question,max){if(phase==='answering')return;clearInterval(prepTimer);phase='answering';$('answerNow').hidden=true;$('endAnswer').disabled=false;$('status').textContent='Đang ghi hình và ghi âm cho Speech-to-Text.';chunks=[];startAudioCapture();recorder=new MediaRecorder(stream);recorder.ondataavailable=e=>e.data.size&&chunks.push(e.data);recorder.start(500);let n=max;$('timer').textContent=`${n}s`;answerTimer=setInterval(()=>{n--;$('timer').textContent=`${n}s`;if(n<=0)finish(question)},1000);$('endAnswer').onclick=()=>finish(question)}
function uploadVideo(video,question){const uploadId=crypto.randomUUID();const upload=video.then(async blob=>{let lastError;for(let attempt=0;attempt<2;attempt++){try{const response=await fetch(api+'/v1/participant/videos',{method:'POST',headers:{...auth(),'Content-Type':blob.type,'X-Interview-Question-Number':String(question.number),'X-Interview-Upload-Id':uploadId},body:blob});if(!response.ok)throw Error(await errorFrom(response));return}catch(error){lastError=error}}throw lastError||Error('Không thể tải video lên')});upload.catch(()=>{});videoUploads.push(upload);return upload}
async function completeInterview(){end('Đang lưu video cuối cùng. Vui lòng giữ trang này mở…','uploading');const results=await Promise.allSettled(videoUploads);const failed=results.some(result=>result.status==='rejected');if(failed){$('ended').dataset.state='upload-failed';$('endMessage').textContent='Bài phỏng vấn đã được ghi nhận, nhưng có video chưa tải lên được. Vui lòng liên hệ HR trước khi đóng trang.';return}phase='completed';$('ended').dataset.state='completed';sessionStorage.removeItem(`interview:${launch}`);$('endMessage').textContent='Cảm ơn bạn. Bài phỏng vấn và toàn bộ video đã được nộp thành công. Bạn có thể đóng trang này.';if(document.fullscreenElement)document.exitFullscreen().catch(()=>{})}
async function finish(question){if(phase!=='answering')return;phase='submitting';clearInterval(answerTimer);$('endAnswer').disabled=true;const wav=stopAudioCapture();const video=new Promise(resolve=>{recorder.onstop=()=>resolve(new Blob(chunks,{type:recorder.mimeType||'video/webm'}));recorder.stop()});uploadVideo(video,question);try{$('status').textContent='Speech-to-Text đang xử lý câu trả lời…';const r=await fetch(api+'/v1/participant/speech/transcribe',{method:'POST',headers:{...auth(),'Content-Type':'audio/wav','X-Interview-Question-Number':String(question.number)},body:wav});if(!r.ok)throw Error(await errorFrom(r));const {text}=await r.json();$('transcript').value=text||'(Không nhận diện được lời nói)';$('status').textContent='AI đang chuẩn bị câu hỏi tiếp theo…';const d=await call('/v1/participant/answers',{method:'POST',headers:auth(),body:JSON.stringify({text})});if(d.status==='COMPLETED')await completeInterview();else showQuestion(d.question,d.prepare_seconds,d.answer_seconds).catch(e=>end(e.message))}catch(e){end(e.message)}}
document.addEventListener('visibilitychange',()=>{if(phase==='interview'||phase==='preparing'||phase==='answering')call('/v1/participant/terminate',{method:'POST',headers:auth(),body:JSON.stringify({reason:'TAB_HIDDEN'})}).finally(()=>end('Phiên đã kết thúc vì bạn rời khỏi tab.'))});document.addEventListener('fullscreenchange',()=>{if(!document.fullscreenElement&&(phase==='interview'||phase==='preparing'||phase==='answering'))call('/v1/participant/terminate',{method:'POST',headers:auth(),body:JSON.stringify({reason:'FULLSCREEN_EXIT'})}).finally(()=>end('Phiên đã kết thúc vì bạn thoát toàn màn hình.'))});load();
