from typing import Dict, Any, Tuple
from app.schemas.matching import EvaluationRequest

class ScoreEngine:
    """
    Computes final scores (0-100) by applying HR weights to the raw metrics 
    generated by the GenericMatchingEngine.
    """
    
    def calculate(self, match_metrics: Dict[str, Any], request: EvaluationRequest) -> Dict[str, float]:
        weights = self._resolve_weights(request)
        
        skills_raw = match_metrics["skills"]["score"]
        exp_raw = match_metrics["experience"]["score"]
        edu_raw = match_metrics["education"]["score"]
        other_raw = match_metrics["other"]["score"]
        
        # Scale to 0-100
        skills_score = round(skills_raw * 100.0, 2)
        exp_score = round(exp_raw * 100.0, 2)
        edu_score = round(edu_raw * 100.0, 2)
        other_score = round(other_raw * 100.0, 2)
        
        total_weight = weights["skills"] + weights["experience"] + weights["education"] + weights["other"]
        if total_weight <= 0: total_weight = 100.0
        
        overall = (
            weights["skills"] * skills_score +
            weights["experience"] * exp_score +
            weights["education"] * edu_score +
            weights["other"] * other_score
        ) / float(total_weight)
        
        overall_score = round(overall, 2)
        
        match_level = "HIGH" if overall_score >= 75.0 else ("MEDIUM" if overall_score >= 50.0 else "LOW")
        
        # Confidence logic based on profile depth
        profile = request.candidate_profile
        data_pts = len(profile.skills) + len(profile.work_experiences) + len(profile.projects) + len(profile.educations) + len(profile.certificates)
        conf = 0.3 if data_pts < 3 else (0.6 if data_pts < 7 else (0.85 if data_pts < 12 else 1.0))
        
        return {
            "overall_score": overall_score,
            "skills_score": skills_score,
            "experience_score": exp_score,
            "education_score": edu_score,
            "other_score": other_score,
            "match_level": match_level,
            "confidence_score": conf
        }

    def _resolve_weights(self, request: EvaluationRequest) -> Dict[str, float]:
        if request.weights:
            return {
                "skills": float(request.weights.skills),
                "experience": float(request.weights.experience),
                "education": float(request.weights.education),
                "other": float(request.weights.other),
            }
        if request.job and request.job.ai_weights_config:
            cfg = request.job.ai_weights_config
            return {
                "skills": float(cfg.skills),
                "experience": float(cfg.experience),
                "education": float(cfg.education),
                "other": float(cfg.other),
            }
        return {"skills": 40.0, "experience": 30.0, "education": 15.0, "other": 15.0}

score_engine = ScoreEngine()
