from typing import Dict, Any, Tuple
from app.schemas.matching import EvaluationRequest

class ScoreEngine:
    """
    Computes final scores (0-100) by applying HR weights to the raw metrics 
    generated by the GenericMatchingEngine.
    """
    
    def calculate(self, match_metrics: Dict[str, Any], request: EvaluationRequest) -> Dict[str, float]:
        weights = self._resolve_weights(request)
        
        skills_raw = match_metrics["skills"]["score"]
        exp_raw = match_metrics["experience"]["score"]
        edu_raw = match_metrics["education"]["score"]
        other_raw = match_metrics["other"]["score"]
        
        # Scale to 0-100
        skills_score = round(skills_raw * 100.0, 2)
        exp_score = round(exp_raw * 100.0, 2)
        edu_score = round(edu_raw * 100.0, 2)
        other_score = round(other_raw * 100.0, 2)
        
        total_weight = weights["skills"] + weights["experience"] + weights["education"] + weights["other"]
        if total_weight <= 0: total_weight = 100.0
        
        overall = (
            weights["skills"] * skills_score +
            weights["experience"] * exp_score +
            weights["education"] * edu_score +
            weights["other"] * other_score
        ) / float(total_weight)
        
        overall_score = round(overall, 2)
        
        # Base match level from score threshold
        base_level = "HIGH" if overall_score >= 75.0 else ("MEDIUM" if overall_score >= 50.0 else "LOW")
        match_level = base_level

        # Enforce level requirement constraints
        level_assessment = match_metrics.get("experience", {}).get("level_assessment")
        if level_assessment:
            req_mode = level_assessment.get("level_requirement_mode", "ADVISORY")
            recommendation = level_assessment.get("recommendation", "")

            if req_mode == "REQUIRED":
                if recommendation == "NOT_ELIGIBLE_LEVEL":
                    # Candidate confirmed below required level → cap to LOW
                    match_level = "LOW"
                    overall_score = min(overall_score, 40.0)
                elif recommendation == "NEEDS_REVIEW":
                    # Can't determine level with confidence → cap to MEDIUM
                    if base_level == "HIGH":
                        match_level = "MEDIUM"
                    overall_score = min(overall_score, 55.0)
        
        # Profile completeness — weighted by importance for matching
        profile = request.candidate_profile
        w_pts = 0.0
        if profile.skills:
            w_pts += 1.5
        if profile.work_experiences:
            w_pts += 3.0  # Most critical for matching
        elif profile.projects:
            w_pts += 1.0  # Partial substitute only
        if profile.educations:
            w_pts += 1.5
        if profile.certificates:
            w_pts += 1.0
        conf = round(min(1.0, w_pts / 7.0), 2)
        
        return {
            "overall_score": overall_score,
            "skills_score": skills_score,
            "experience_score": exp_score,
            "education_score": edu_score,
            "other_score": other_score,
            "match_level": match_level,
            "confidence_score": conf,
            "level_assessment": level_assessment,
        }

    def _resolve_weights(self, request: EvaluationRequest) -> Dict[str, float]:
        if request.weights:
            return {
                "skills": float(request.weights.skills),
                "experience": float(request.weights.experience),
                "education": float(request.weights.education),
                "other": float(request.weights.other),
            }
        if request.job and request.job.ai_weights_config:
            cfg = request.job.ai_weights_config
            return {
                "skills": float(cfg.skills),
                "experience": float(cfg.experience),
                "education": float(cfg.education),
                "other": float(cfg.other),
            }
        return {"skills": 40.0, "experience": 30.0, "education": 15.0, "other": 15.0}

score_engine = ScoreEngine()
